name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set up Production Environment
        run: echo "Setting up production environment..."

      - name: Run Tests
        run: echo "Running tests..."

      - name: Build Artifacts
        run: echo "Building artifacts..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to development
        run: echo "Deploying to development environment..."
